DROP TABLE IF EXISTS sales CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
  payment_status VARCHAR(30) NOT NULL,
  order_date DATE NOT NULL
);
