DROP TABLE IF EXISTS books_in_order CASCADE;
CREATE TABLE books_in_order (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES sales(id) ON DELETE CASCADE,
  book_id INTEGER REFERENCES books(id) ON DELETE CASCADE
);
